/**
 * The words an enquiry turns into, and the HTML they are rendered in.
 *
 * A package rather than a file in the admin panel for the same reason the SEO
 * graph is one: the office edits these templates in a screen that must show
 * what will actually be sent. One renderer, called by the admin to preview and
 * by whichever app delivers, means the preview cannot drift from the message.
 *
 * ## Why the templates are rows and not files
 *
 * "Thank you for writing to us" is copy, and copy is the office's, not the
 * developer's. Every field here may carry tokens — `{{name}}`, `{{trip}}` —
 * and the token list is fixed per kind, so an editor can rewrite the whole
 * message without a deploy and cannot reference a variable that does not
 * exist.
 *
 * ## Why the HTML looks like 2004
 *
 * Tables, inline styles, no flexbox, no custom properties. Not taste: Outlook
 * on Windows renders through Word, which supports none of it. The design
 * system's tokens are resolved to literal hex values *here*, at the one
 * boundary where the rule against hardcoded colours does not apply, because
 * the alternative is an email that arrives unstyled.
 */

export type EmailKind =
  | 'ENQUIRY_ACKNOWLEDGEMENT'
  | 'ENQUIRY_NOTIFICATION'
  | 'NEWSLETTER_WELCOME'
  | 'NEWSLETTER_CONFIRM'
  | 'PASSWORD_RESET';

/** The words one kind of message is made of. Every field may carry tokens. */
export interface EmailTemplate {
  kind: EmailKind;
  name: string;
  isActive: boolean;
  subject: string;
  /** The line the inbox shows after the subject. Never rendered in the body. */
  preheader: string;
  eyebrow: string;
  heading: string;
  /** Blank lines separate paragraphs. */
  intro: string;
  closing: string;
  summaryLabel: string;
  notesLabel: string;
  buttonLabel: string;
  /** Relative to the site, or absolute. Blank hides the button. */
  buttonUrl: string;
  signOff: string;
  footNote: string;
}

/** Who is sending, resolved from the one company record. */
export interface EmailIdentity {
  name: string;
  email: string;
  phone: string;
  siteUrl: string;
  addressLine: string;
  /** Absolute URL to a small logo, or blank. */
  logoUrl: string;
}

/** The enquiry a message is about, as the renderer reads it. */
export interface EmailEnquiry {
  reference: string;
  name: string;
  email: string;
  phone?: string;
  country?: string;
  tripTitle?: string;
  preferredDates?: string;
  travellers?: string;
  message?: string;
  restDays?: boolean;
  source?: string;
  /**
   * An operational note to the office, drawn above everything else.
   *
   * Not copy, and deliberately not editable: it says something about this
   * message that the office must not be able to switch off — at present, that
   * the enquiry reached nobody's inbox but this one, because the panel could
   * not be reached to record it. An enquiry that exists only as an email looks
   * exactly like one that is safely in the system, and that is how a lead is
   * lost twice.
   *
   * Ignored on the traveller's copy, which is not the place for it.
   */
  notice?: string;
  origin?: {
    pagePath?: string;
    utmSource?: string;
    utmMedium?: string;
    utmCampaign?: string;
  };
}

export interface RenderedEmail {
  subject: string;
  html: string;
  /**
   * The plain-text alternative.
   *
   * Not optional and not generated by stripping tags from the HTML. A
   * multipart message without one is scored as spam by most filters, and a
   * text part made by regex over a table layout is a column of stray
   * whitespace.
   */
  text: string;
}

/* -------------------------------------------------------------------------- */
/*  Tokens                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * What each kind of message may reference.
 *
 * Exported so the admin's template editor can list them beside the field and
 * validate on save. A template naming `{{departure}}` should fail in the
 * editor, not render as the literal string in somebody's inbox.
 */
export const TEMPLATE_TOKENS: Record<EmailKind, string[]> = {
  ENQUIRY_ACKNOWLEDGEMENT: [
    'name',
    'firstName',
    'reference',
    'trip',
    'dates',
    'travellers',
    'company',
    'phone',
    'email',
    'replyPromise',
  ],
  ENQUIRY_NOTIFICATION: [
    'name',
    'firstName',
    'reference',
    'trip',
    'dates',
    'travellers',
    'country',
    'contactEmail',
    'contactPhone',
    'source',
    'company',
  ],
  NEWSLETTER_WELCOME: ['name', 'firstName', 'company', 'siteUrl'],
  NEWSLETTER_CONFIRM: ['name', 'firstName', 'company', 'confirmUrl'],
  PASSWORD_RESET: ['name', 'firstName', 'resetUrl', 'expiryMinutes', 'company'],
};

/**
 * Substitutes `{{token}}`.
 *
 * An unknown token is replaced with an empty string rather than left in place.
 * Leaving it renders `{{deparutre}}` to a customer; removing it renders a
 * sentence with a gap, which is the better of the two failures — and the
 * editor already refused to save it.
 */
export function fill(text: string, values: Record<string, string>): string {
  return text.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_match, key: string) =>
    values[key] ?? '',
  );
}

/* -------------------------------------------------------------------------- */
/*  Palette                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * The design tokens, resolved.
 *
 * The one place in this repository where a hex literal is correct. These are
 * the published values of `--ink`, `--paper`, `--paper-2`, `--gold`,
 * `--saffron`, `--pine` and `--line`; when a token changes, this changes with
 * it, and the comment is the reminder that it has to be done by hand.
 */
const C = {
  ink: '#1A1A18',
  muted: '#6B6B66',
  paper: '#FFFFFF',
  paper2: '#F7F7F6',
  line: '#E4E2DD',
  gold: '#B08A44',
  saffron: '#D9770F',
  pine: '#1F3229',
} as const;

const FONT =
  "'Commissioner', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Blank-line-separated prose → paragraphs. */
function paragraphs(text: string): string {
  return text
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map(
      (p) =>
        `<p style="margin:0 0 16px;font-size:16px;line-height:1.65;color:${C.ink};">${escapeHtml(
          p,
        ).replace(/\n/g, '<br>')}</p>`,
    )
    .join('');
}

function summaryTable(rows: [string, string][]): string {
  const cells = rows
    .filter(([, value]) => value && value.trim().length > 0)
    .map(
      ([label, value]) => `
        <tr>
          <td style="padding:10px 16px 10px 0;font-size:13px;letter-spacing:0.06em;text-transform:uppercase;color:${C.muted};border-bottom:1px solid ${C.line};white-space:nowrap;vertical-align:top;">${escapeHtml(
            label,
          )}</td>
          <td style="padding:10px 0;font-size:15px;line-height:1.5;color:${C.ink};border-bottom:1px solid ${C.line};">${escapeHtml(
            value,
          )}</td>
        </tr>`,
    )
    .join('');

  if (!cells) return '';
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;margin:0 0 24px;">${cells}</table>`;
}

/**
 * The shell every message is drawn in.
 *
 * 600 px, centred, one column. `width` attributes as well as CSS because
 * Outlook ignores the second; `role="presentation"` so a screen reader does
 * not announce the layout as four nested tables.
 */
function shell(args: {
  identity: EmailIdentity;
  preheader: string;
  eyebrow: string;
  heading: string;
  body: string;
  footNote: string;
}): string {
  const { identity } = args;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<title>${escapeHtml(args.heading)}</title>
</head>
<body style="margin:0;padding:0;background:${C.paper2};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${escapeHtml(
    args.preheader,
  )}</div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:${C.paper2};">
  <tr>
    <td align="center" style="padding:32px 16px;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="width:100%;max-width:600px;background:${C.paper};border:1px solid ${C.line};">
        <tr>
          <td style="padding:32px 32px 0;">
            ${
              identity.logoUrl
                ? `<img src="${escapeHtml(identity.logoUrl)}" alt="${escapeHtml(
                    identity.name,
                  )}" width="120" style="display:block;border:0;margin:0 0 28px;">`
                : `<div style="font-size:18px;letter-spacing:0.1em;text-transform:uppercase;color:${C.ink};margin:0 0 28px;">${escapeHtml(
                    identity.name,
                  )}</div>`
            }
            ${
              args.eyebrow
                ? `<div style="font-size:12px;letter-spacing:0.18em;text-transform:uppercase;color:${C.gold};margin:0 0 10px;">${escapeHtml(
                    args.eyebrow,
                  )}</div>`
                : ''
            }
            <h1 style="margin:0 0 24px;font-family:${FONT};font-size:26px;line-height:1.25;font-weight:400;color:${C.ink};">${escapeHtml(
              args.heading,
            )}</h1>
          </td>
        </tr>
        <tr><td style="padding:0 32px;font-family:${FONT};">${args.body}</td></tr>
        <tr>
          <td style="padding:28px 32px 32px;border-top:1px solid ${C.line};font-family:${FONT};">
            <p style="margin:0 0 6px;font-size:13px;line-height:1.6;color:${C.muted};">
              ${[
                `<strong style="color:${C.ink};font-weight:500;">${escapeHtml(identity.name)}</strong>`,
                escapeHtml(identity.addressLine),
                /* Each line only when there is something on it, and the middle
                   dot only when it has something on both sides. A blank field
                   used to render as an empty line and a stranded "·" — which
                   nobody saw until a message had to be written without the
                   company record to hand. */
                [
                  identity.phone &&
                    `<a href="tel:${escapeHtml(identity.phone.replace(/\s+/g, ''))}" style="color:${C.muted};text-decoration:none;">${escapeHtml(
                      identity.phone,
                    )}</a>`,
                  identity.email &&
                    `<a href="mailto:${escapeHtml(identity.email)}" style="color:${C.muted};text-decoration:none;">${escapeHtml(
                      identity.email,
                    )}</a>`,
                ]
                  .filter(Boolean)
                  .join(' · '),
              ]
                .filter(Boolean)
                .join('<br>')}
            </p>
            ${
              args.footNote
                ? `<p style="margin:12px 0 0;font-size:12px;line-height:1.6;color:${C.muted};">${escapeHtml(
                    args.footNote,
                  )}</p>`
                : ''
            }
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>`;
}

function button(label: string, url: string): string {
  if (!label || !url) return '';
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 28px;">
    <tr><td style="background:${C.saffron};">
      <a href="${escapeHtml(url)}" style="display:inline-block;padding:14px 28px;font-family:${FONT};font-size:14px;letter-spacing:0.08em;text-transform:uppercase;color:#FFFFFF;text-decoration:none;">${escapeHtml(
        label,
      )}</a>
    </td></tr>
  </table>`;
}

/* -------------------------------------------------------------------------- */
/*  Render                                                                     */
/* -------------------------------------------------------------------------- */

export interface RenderEnquiryArgs {
  template: EmailTemplate;
  identity: EmailIdentity;
  enquiry: EmailEnquiry;
  /** The office's copy carries the contact details and the attribution. */
  audience: 'traveller' | 'office';
  replyPromise?: string;
}

export function renderEnquiryEmail(args: RenderEnquiryArgs): RenderedEmail {
  const { template, identity, enquiry, audience } = args;

  const values: Record<string, string> = {
    name: enquiry.name,
    firstName: enquiry.name.split(' ')[0] ?? enquiry.name,
    reference: enquiry.reference,
    trip: enquiry.tripTitle ?? '',
    dates: enquiry.preferredDates ?? '',
    travellers: enquiry.travellers ?? '',
    country: enquiry.country ?? '',
    contactEmail: enquiry.email,
    contactPhone: enquiry.phone ?? '',
    source: enquiry.source ?? '',
    company: identity.name,
    phone: identity.phone,
    email: identity.email,
    siteUrl: identity.siteUrl,
    replyPromise: args.replyPromise ?? '',
  };

  const rows: [string, string][] = [
    ['Reference', enquiry.reference],
    ['Journey', enquiry.tripTitle ?? 'Not yet chosen'],
    ['When', enquiry.preferredDates ?? 'Flexible'],
    ['Travellers', enquiry.travellers ?? ''],
  ];

  if (audience === 'office') {
    rows.push(
      ['Name', enquiry.name],
      ['Email', enquiry.email],
      ['Phone', enquiry.phone ?? ''],
      ['Country', enquiry.country ?? ''],
      ['Rest days', enquiry.restDays ? 'Wanted' : ''],
      ['Form', enquiry.source ?? ''],
      ['Page', enquiry.origin?.pagePath ?? ''],
      ['Campaign', enquiry.origin?.utmCampaign ?? ''],
    );
  }

  const summaryLabel = fill(template.summaryLabel, values);
  const notesLabel = fill(template.notesLabel, values);

  const body = [
    audience === 'office' && enquiry.notice ? banner(enquiry.notice) : '',
    paragraphs(fill(template.intro, values)),
    summaryLabel ? heading(summaryLabel) : '',
    summaryTable(rows),
    enquiry.message ? heading(notesLabel || 'In their words') : '',
    enquiry.message
      ? `<div style="padding:16px 20px;background:${C.paper2};border-left:2px solid ${C.gold};margin:0 0 24px;"><p style="margin:0;font-size:15px;line-height:1.65;color:${C.ink};">${escapeHtml(
          enquiry.message,
        ).replace(/\n/g, '<br>')}</p></div>`
      : '',
    button(fill(template.buttonLabel, values), resolveUrl(identity, fill(template.buttonUrl, values))),
    paragraphs(fill(template.closing, values)),
    template.signOff
      ? `<p style="margin:0 0 24px;font-size:16px;line-height:1.65;color:${C.ink};">${escapeHtml(
          fill(template.signOff, values),
        ).replace(/\n/g, '<br>')}</p>`
      : '',
  ].join('');

  return {
    /**
     * Whitespace closed up after substitution, not before.
     *
     * `Enquiry {{reference}} — {{name}}` with no reference is
     * `Enquiry  — Anne Traveller`, and a subject line is the one place a
     * doubled space is conspicuous. Only the subject is treated this way: the
     * body's blank lines are paragraphs.
     */
    subject: fill(template.subject, values).replace(/\s+/g, ' ').trim(),
    html: shell({
      identity,
      preheader: fill(template.preheader, values),
      eyebrow: fill(template.eyebrow, values),
      heading: fill(template.heading, values),
      body,
      footNote: fill(template.footNote, values),
    }),
    text: plainText({
      notice: audience === 'office' ? enquiry.notice : undefined,
      heading: fill(template.heading, values),
      intro: fill(template.intro, values),
      rows,
      message: enquiry.message,
      closing: fill(template.closing, values),
      signOff: fill(template.signOff, values),
      identity,
    }),
  };
}

/**
 * The one thing in the message that is louder than the message.
 *
 * Saffron rather than gold, and a solid rule rather than a tint, because it is
 * read by somebody scanning a familiar email for what is new in it.
 */
function banner(text: string): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;"><tr><td style="padding:14px 18px;background:#FDF4E7;border-left:4px solid ${C.saffron};"><p style="margin:0;font-size:15px;line-height:1.55;font-weight:500;color:${C.ink};">${escapeHtml(
    text,
  )}</p></td></tr></table>`;
}

function heading(text: string): string {
  return `<h2 style="margin:28px 0 12px;font-size:13px;letter-spacing:0.16em;text-transform:uppercase;font-weight:500;color:${C.gold};">${escapeHtml(
    text,
  )}</h2>`;
}

function resolveUrl(identity: EmailIdentity, url: string): string {
  if (!url) return '';
  if (/^https?:\/\//i.test(url) || url.startsWith('mailto:') || url.startsWith('tel:')) {
    return url;
  }
  return `${identity.siteUrl.replace(/\/$/, '')}${url.startsWith('/') ? url : `/${url}`}`;
}

/** Written from the same inputs as the HTML, never derived from it. */
function plainText(args: {
  notice?: string;
  heading: string;
  intro: string;
  rows: [string, string][];
  message?: string;
  closing: string;
  signOff: string;
  identity: EmailIdentity;
}): string {
  const lines: string[] = [];
  /* Before the heading, not after it: the plain-text part is what a phone
     notification and every screen reader quote first. */
  if (args.notice) lines.push(`** ${args.notice} **`, '');
  lines.push(args.heading, '='.repeat(args.heading.length), '');
  if (args.intro) lines.push(args.intro, '');
  for (const [label, value] of args.rows) {
    if (value && value.trim()) lines.push(`${label}: ${value}`);
  }
  lines.push('');
  if (args.message) lines.push('In their words:', args.message, '');
  if (args.closing) lines.push(args.closing, '');
  if (args.signOff) lines.push(args.signOff, '');
  lines.push(
    '--',
    ...[
      args.identity.name,
      args.identity.addressLine,
      [args.identity.phone, args.identity.email].filter(Boolean).join(' · '),
      args.identity.siteUrl,
    ].filter(Boolean),
  );
  return lines.join('\n');
}

/**
 * The templates a fresh install starts with.
 *
 * Seeded into the database rather than used as a fallback, so the office can
 * edit every word of them on day one. A code-level fallback would be words
 * nobody can change without a developer, which is the problem this whole
 * screen exists to solve.
 */
export const DEFAULT_TEMPLATES: EmailTemplate[] = [
  {
    kind: 'ENQUIRY_ACKNOWLEDGEMENT',
    name: 'Enquiry — to the traveller',
    isActive: true,
    subject: 'Your enquiry — {{company}}',
    preheader: 'We have your note and will write back personally.',
    eyebrow: 'Thank you',
    heading: 'We have your note',
    intro:
      'Dear {{firstName}},\n\nThank you for writing to us. Someone here reads every enquiry themselves, and we will come back to you with a considered answer rather than a brochure.\n\n{{replyPromise}}.',
    closing:
      'If anything changes in the meantime — dates, numbers, or what you are hoping for — simply reply to this message.',
    summaryLabel: 'What you told us',
    notesLabel: 'Your note',
    buttonLabel: 'See our journeys',
    buttonUrl: '/trips',
    signOff: 'With warm regards,\n{{company}}',
    footNote:
      'This message was sent because you made an enquiry at lotuspeak.org. We do not add enquiries to a mailing list.',
  },
  {
    kind: 'ENQUIRY_NOTIFICATION',
    name: 'Enquiry — to the office',
    isActive: true,
    /**
     * No `{{trip}}` in the subject.
     *
     * It was `{{reference}} — {{name}}{{trip}}`, which reads as "Anne
     * TravellerJomolhari trek" when a journey is named and leaves a dangling
     * dash when one is not. Tokens substitute, they do not join — so anything
     * optional belongs in the body, where the summary table already has a row
     * for it and prints "Not yet chosen" when it is empty.
     */
    subject: 'Enquiry {{reference}} — {{name}}',
    preheader: '{{name}} has written in.',
    eyebrow: 'New enquiry',
    heading: '{{name}} has written',
    intro: 'An enquiry arrived from the {{source}} form.',
    closing: 'Open it in the admin panel to reply, assign it, or add a note.',
    summaryLabel: 'The enquiry',
    notesLabel: 'In their words',
    buttonLabel: 'Open in the admin panel',
    buttonUrl: '',
    signOff: '',
    footNote: 'Sent automatically by the Lotus Peak admin panel.',
  },
  {
    kind: 'NEWSLETTER_WELCOME',
    name: 'Newsletter — welcome',
    isActive: true,
    subject: 'Welcome — {{company}}',
    preheader: 'A few letters a year, from Bhutan.',
    eyebrow: 'Welcome',
    heading: 'Thank you for joining us',
    intro:
      'Dear {{firstName}},\n\nWe write a few times a year: when a festival date is fixed, when the cranes arrive in Phobjikha, and when we have something worth saying. Never more often than that.',
    closing: '',
    summaryLabel: '',
    notesLabel: '',
    buttonLabel: 'Read the journal',
    buttonUrl: '/journal',
    signOff: 'With warm regards,\n{{company}}',
    footNote: 'You can unsubscribe from any letter we send, in one click.',
  },
  {
    kind: 'NEWSLETTER_CONFIRM',
    name: 'Newsletter — confirm the address',
    isActive: true,
    subject: 'Please confirm your email — {{company}}',
    preheader: 'One click, and we will know the address is yours.',
    eyebrow: 'One more step',
    heading: 'Please confirm your email',
    intro:
      'Somebody — we hope you — asked for our letters at this address. Confirm it below and we will add you.',
    closing: 'If it was not you, ignore this message and nothing will happen.',
    summaryLabel: '',
    notesLabel: '',
    buttonLabel: 'Confirm my email',
    buttonUrl: '{{confirmUrl}}',
    signOff: '',
    footNote: 'This link expires in seven days.',
  },
  {
    kind: 'PASSWORD_RESET',
    name: 'Admin — password reset',
    isActive: true,
    subject: 'Reset your password — {{company}} admin',
    preheader: 'A link to set a new password.',
    eyebrow: 'Admin panel',
    heading: 'Set a new password',
    intro:
      'Hello {{firstName}},\n\nSomebody asked to reset the password on your admin account. Use the link below to set a new one.',
    closing:
      'If you did not ask for this, nothing has changed and you can ignore this message. Tell whoever runs the panel, though — somebody typed your address.',
    summaryLabel: '',
    notesLabel: '',
    buttonLabel: 'Set a new password',
    buttonUrl: '{{resetUrl}}',
    signOff: '',
    footNote: 'This link expires in {{expiryMinutes}} minutes and works once.',
  },
];
