import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * Next's recommended rules, plus the two this panel needs relaxed.
 *
 * `no-img-element` fires on every thumbnail in the media library and the
 * pickers. Those are deliberate: `next/image` optimises through a route that
 * would re-encode sixty thumbnails of images this app has *already* built
 * renditions for, which is work the media pipeline did on upload.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      '@next/next/no-img-element': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        /* `const { key: _key, ...rest }` is how a form strips a field before
           sending it, and it is clearer than a delete. */
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
    },
  },
  /* `next-env.d.ts` is generated by Next on every build and carries a triple-
     slash reference the rule forbids. It is not ours to edit. */
  { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
];

export default config;
